[ 2023-08-06 14:39:44,437 ] 225 werkzeug - WARNING -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
[ 2023-08-06 14:39:44,437 ] 225 werkzeug - INFO -  * Running on http://192.168.90.81:5000/ (Press CTRL+C to quit)
[ 2023-08-06 14:39:46,688 ] 225 werkzeug - INFO - 192.168.90.81 - - [06/Aug/2023 14:39:46] "GET / HTTP/1.1" 200 -
[ 2023-08-06 14:39:59,979 ] 225 werkzeug - INFO - 192.168.90.81 - - [06/Aug/2023 14:39:59] "GET /predictdata HTTP/1.1" 200 -
[ 2023-08-06 14:40:09,372 ] 1891 app - ERROR - Exception on /predictdata [POST]
Traceback (most recent call last):
  File "C:\Users\PC-KSS\mlproject-main\src\pipeline\predict_pipeline.py", line 13, in predict
    model_path=os.path.join("artifacts","model.pkl")
NameError: name 'os' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\PC-KSS\anaconda3\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\PC-KSS\anaconda3\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\PC-KSS\anaconda3\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\PC-KSS\anaconda3\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\PC-KSS\anaconda3\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\PC-KSS\anaconda3\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\PC-KSS\mlproject-main\app.py", line 39, in predict_datapoint
    results=predict_pipeline.predict(pred_df)
  File "C:\Users\PC-KSS\mlproject-main\src\pipeline\predict_pipeline.py", line 24, in predict
    raise CustomException(e,sys)
src.exception.CustomException: Error occured in python script name [C:\Users\PC-KSS\mlproject-main\src\pipeline\predict_pipeline.py] line number [13] error message[name 'os' is not defined]
[ 2023-08-06 14:40:09,374 ] 225 werkzeug - INFO - 192.168.90.81 - - [06/Aug/2023 14:40:09] "[35m[1mPOST /predictdata HTTP/1.1[0m" 500 -
